import { Inter } from "next/font/google";
import MUI_Wrapper from "./components/MUI_Wrapper";
import "./globals.css";

import { Poppins } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
}); // Or any specific subsets

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="root" className={`${poppins.className} poppins`}>
        <MUI_Wrapper>{children}</MUI_Wrapper>
      </body>
    </html>
  );
}
